/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 11/11/2023 16:08:39        ****/
/******************************************************************************/

/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR G_ID_BOMBA;
CREATE GENERATOR G_ID_PRODUTO;
CREATE GENERATOR G_ID_TANQUE;
CREATE GENERATOR G_ID_VENDA;


/******************************************************************************/
/****                              Exceptions                              ****/
/******************************************************************************/

/******************************************************************************/
/****                              Procedures                              ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^



/******************************************************************************/
/****                           Tables and Views                           ****/
/******************************************************************************/

CREATE TABLE TB_BOMBA (
    ID_BOMBA INTEGER NOT NULL,
    ID_TANQUE INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL);


CREATE TABLE TB_PRODUTO (
    ID_PRODUTO INTEGER NOT NULL,
    VR_VENDA NUMERIC(15,2) NOT NULL,
    VR_CUSTO NUMERIC(15,2) NOT NULL,
    QTDE_ESTOQUE NUMERIC(15,2) NOT NULL,
    PER_IMPOSTO NUMERIC(15,2) NOT NULL,
    DESCRICAO VARCHAR(50) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252);


CREATE TABLE TB_TANQUE (
    ID_TANQUE INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    CAPACIDADE NUMERIC(15,2),
    NUMERO INTEGER NOT NULL);


CREATE TABLE TB_VENDA (
    ID_VENDA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    ID_TANQUE INTEGER NOT NULL,
    ID_BOMBA INTEGER NOT NULL,
    DATA DATE NOT NULL,
    HORA TIME NOT NULL,
    QTDE NUMERIC(15,2) NOT NULL,
    VR_VENDA NUMERIC(15,2) NOT NULL,
    VR_CUSTO NUMERIC(15,2) NOT NULL,
    VR_TOTAL NUMERIC(15,2) NOT NULL,
    PER_IMPOSTO NUMERIC(15,2) NOT NULL,
    BC_IMPOSTO NUMERIC(15,2) NOT NULL,
    VR_IMPOSTO NUMERIC(15,2) NOT NULL);




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/


ALTER TABLE TB_BOMBA ADD CONSTRAINT PK_TB_BOMBA PRIMARY KEY (ID_BOMBA);
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_TB_PRODUTO PRIMARY KEY (ID_PRODUTO);
ALTER TABLE TB_TANQUE ADD CONSTRAINT PK_TB_TANQUE PRIMARY KEY (ID_TANQUE);
ALTER TABLE TB_VENDA ADD CONSTRAINT PK_TB_VENDA PRIMARY KEY (ID_VENDA);

/******************************************************************************/
/****                          Unique constraints                          ****/
/******************************************************************************/



/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/


ALTER TABLE TB_BOMBA ADD CONSTRAINT FK_TB_BOMBA_ID_TANQUE FOREIGN KEY (ID_TANQUE) REFERENCES TB_TANQUE (ID_TANQUE);
ALTER TABLE TB_TANQUE ADD CONSTRAINT FK_TB_TANQUE_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO);
ALTER TABLE TB_VENDA ADD CONSTRAINT FK_TB_VENDA_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO);
ALTER TABLE TB_VENDA ADD CONSTRAINT FK_TB_VENDA_ID_TANQUE FOREIGN KEY (ID_TANQUE) REFERENCES TB_TANQUE (ID_TANQUE);
ALTER TABLE TB_VENDA ADD CONSTRAINT FK_TB_VENDA_ID_BOMBA FOREIGN KEY (ID_BOMBA) REFERENCES TB_BOMBA (ID_BOMBA);

/******************************************************************************/
/****                          Check constraints                           ****/
/******************************************************************************/



/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/



/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^

/******************************************************************************/
/****                              Procedures                              ****/
/******************************************************************************/

SET TERM ^ ;

SET TERM ; ^

